- hosts: localhost
  tasks:
  - name: "Artifact integration test results to the web"
    local_action: 'shell curl -F "file=@integration_results.txt" https://file.io'
    register: result

  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        integration_results_url:  "{{ (result.stdout|from_json).link }}"
    register: url
        
  - name: "Debug the Stat"
    debug:
      var: integration_results_url
    ignore_errors: true
  
  - name: "Debug again"
    debug:
      msg: "{{ hostvars.localhost.url.ansible_stats.data }}"
