---
- name: Print Messages 1
  hosts: "{{ ansible_play_hosts[0:2] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: first group 1 2 3
      debug:
        msg: "Host: {{ item }}"

- name: Print Messages 2
  hosts: "{{ ansible_play_hosts[3:5] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: second group 4 5 6
      debug:
        msg: "Host: {{ item }}"

- name: Print Messages 3
  hosts: "{{ ansible_play_hosts[6:8] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: third group 7 8 9
      debug:
        msg: "Host: {{ item }}"
      
- name: Print Messages 4
  hosts: "{{ ansible_play_hosts[9:11] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: fourth group 10 11 12
      debug:
        msg: "Host: {{ item }}"
