---      
- name: Print Messages 1
  hosts: "{{ ansible_play_hosts[0:3] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: first group 1 2 3
      ping:
      ignore_unreachable: true

- name: Print Messages 2
  hosts: "{{ ansible_play_hosts[3:3] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: second group 4 5 6
      ping:
      ignore_unreachable: true


- name: Print Messages 3
  hosts: "{{ ansible_play_hosts[6:3] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: third group 7 8 9
      ping:
      ignore_unreachable: true
      
- name: Print Messages 4
  hosts: "{{ ansible_play_hosts[9:3] }}"
  become: true
  gather_facts: false
  
  tasks:
    - name: fourth group 10 11 12
      ping:
      ignore_unreachable: true
